version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      
  mongo:
    image: mongo:latest
    command: --bind_ip 0.0.0.0
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=moodbot
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  mongodb_data:
  redis_data:
