version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - shared
  
  mongo:
    image: mongo:latest
    command: --bind_ip 0.0.0.0
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=moodbot
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - shared

  mysql:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: remoodle_aitu
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - shared
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 2s
      retries: 20

volumes:
  redis_data:
  mongodb_data:
  mysql_data:

networks:
  shared:
    name: r1ng
    external: true