#:schema node_modules/wrangler/config-schema.json
name = "alert-point"
main = "src/index.ts"
compatibility_date = "2024-05-24"
compatibility_flags = ["nodejs_compat"]

account_id = "2351e8b1323560cbfbad4752ca226fd8"
keep_vars = true

[vars]
TELEGRAM_CHAT_ID = "-1002242666096"