version: "3.8"

services:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - shared

  mongo:
    image: mongo:latest
    # command: --bind_ip 0.0.0.0
    restart: always
    # environment:
    #   - MONGO_INITDB_DATABASE=moodbot
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - shared

  mysql:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_DATABASE: remoodle_aitu
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - shared
    ports:
      - "127.0.0.1:3306:3306"
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   timeout: 2s
    #   retries: 20

networks:
  shared:
    name: r1ng
    external: true
