export type MoodleIntroAttachment = {
  filename: string;
  filepath: string;
  filesize: number;
  fileurl: string;
  timemodified: number;
  mimetype: string;
  isexternalfile: boolean;
};

export type MoodleAssignment = {
  id: number;
  cmid: number;
  course: number;
  name: string;
  nosubmissions: number;
  submissiondrafts: number;
  sendnotifications: number;
  sendlatenotifications: number;
  sendstudentnotifications: number;
  duedate: number;
  allowsubmissionsfromdate: number;
  grade: number;
  timemodified: number;
  completionsubmit: number;
  cutoffdate: number;
  gradingduedate: number;
  teamsubmission: number;
  requireallteammemberssubmit: number;
  teamsubmissiongroupingid: number;
  blindmarking: number;
  hidegrader: number;
  revealidentities: number;
  attemptreopenmethod: string;
  maxattempts: number;
  markingworkflow: number;
  markingallocation: number;
  requiresubmissionstatement: number;
  preventsubmissionnotingroup: number;
  configs: Array<any>;
  intro: string;
  introformat: number;
  introfiles: Array<any>;
  introattachments: Array<MoodleIntroAttachment>;
};

export type MoodleCourseClassification = "inprogress" | "past" | "future";

export type MoodleCourse = {
  id: number;
  fullname: string;
  shortname: string;
  idnumber: string;
  summary: string | null;
  summaryformat: number | null;
  startdate: number;
  enddate: number;
  visible: boolean;
  showactivitydates: boolean | null;
  showcompletionconditions: boolean | null;
  pdfexportfont: string | null;
  fullnamedisplay: string;
  viewurl: string;
  courseimage: string;
  progress: number;
  hasprogress: boolean;
  isfavourite: boolean;
  hidden: boolean;
  timeaccess: number;
  showshortname: boolean;
  coursecategory: string;
};

export type MoodleCourseContentModuleContent = {
  type: string | null;
  filename: string | null;
  filepath: string | null;
  filesize: number | null;
  fileurl: string | null;
  content: string | null;
  timecreated: number | null;
  timemodified: number | null;
  sortorder: number | null;
  mimetype: string | null;
  isexternalfile: boolean | null;
  repositorytype: string | null;
  userid: number | null;
  author: string | null;
  license: string | null;
};

export type MoodleCourseContentModule = {
  id: number | null;
  url: string | null;
  name: string | null;
  instance: number | null;
  contextid: number | null;
  description: string | null;
  visible: number | null;
  uservisible: boolean | null;
  availabilityinfo: string | null;
  visibleoncoursepage: number | null;
  modicon: string | null;
  modname: string | null;
  modplural: string | null;
  availability: string | null;
  indent: number | null;
  onclick: string | null;
  afterlink: string | null;
  customdata: string | null;
  noviewlink: boolean | null;
  completion: number | null;
  downloadcontent: number | null;
  contents?: MoodleCourseContentModuleContent[];
};

export type MoodleCourseContent = {
  id: number;
  name: string;
  visible: number;
  summaryformat: number;
  hiddenbynumsections: number;
  summary: string;
  section: number;
  uservisible: boolean;
  modules: MoodleCourseContentModule[];
};

export type MoodleEvent = {
  id: number;
  name: string;
  description: string;
  descriptionformat: number;
  location: string;
  categoryid: any;
  groupid?: number;
  userid?: number;
  repeatid: any;
  eventcount: any;
  component: string;
  modulename: string;
  instance: number;
  eventtype: string;
  timestart: number;
  timeduration: number;
  timesort: number;
  timeusermidnight: number;
  visible: number;
  timemodified: number;
  icon: {
    key: string;
    component: string;
    alttext: string;
  };
  course: {
    id: number;
    fullname: string;
    shortname: string;
    idnumber: string;
    summary: string;
    summaryformat: number;
    startdate: number;
    enddate: number;
    visible: boolean;
    showactivitydates: boolean;
    showcompletionconditions?: boolean;
    fullnamedisplay: string;
    viewurl: string;
    courseimage: string;
    progress: number;
    hasprogress: boolean;
    isfavourite: boolean;
    hidden: boolean;
    showshortname: boolean;
    coursecategory: string;
  };
  subscription: {
    displayeventsource: boolean;
  };
  canedit: boolean;
  candelete: boolean;
  deleteurl: string;
  editurl: string;
  viewurl: string;
  formattedtime: string;
  isactionevent: boolean;
  iscourseevent: boolean;
  iscategoryevent: boolean;
  groupname?: string;
  normalisedeventtype: string;
  normalisedeventtypetext: string;
  action?: {
    name: string;
    url: string;
    itemcount: number;
    actionable: boolean;
    showitemcount: boolean;
  };
  url: string;
};

export type MoodleGrade = {
  id: number;
  itemname: string;
  itemtype: string;
  itemmodule?: string;
  iteminstance?: number;
  itemnumber?: number;
  idnumber: string;
  categoryid?: number;
  outcomeid: any;
  scaleid: any;
  locked: any;
  graderaw?: number;
  gradedatesubmitted?: number;
  gradedategraded?: number;
  gradehiddenbydate: boolean;
  gradeneedsupdate: boolean;
  gradeishidden: boolean;
  gradeislocked: any;
  gradeisoverridden: any;
  gradeformatted: string;
  grademin: number;
  grademax: number;
  rangeformatted: string;
  percentageformatted: string;
  feedback: string;
  feedbackformat: number;
  cmid?: number;
};
