version: '3.8'

services:
  redis:
    image: redis:latest
    volumes:
      - ./data/redis:/data
    networks:
      - shared
  
  mongo:
    image: mongo:latest
    command: --bind_ip 0.0.0.0
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=moodbot
    volumes:
      - ./data/mongo:/data/db
    networks:
      - shared

  mysql:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: remoodle_aitu
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - shared
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 2s
      retries: 20

networks:
  shared:
    name: r1ng
    external: true