name: phpstan-analyse

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpstan:
    name: PHPStan

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: PHPStan
      uses: docker://oskarstark/phpstan-ga
      env:
        CHECK_PLATFORM_REQUIREMENTS: false
      with:
        args: analyse --level=5 -c phpstan.neon
