name: "[api] Publish Docker image"

on:
  push:
    branches: [main]
    paths:
      - "remoodle/api/**"
      - ".github/workflows/api-docker.yml"

  workflow_dispatch:

env:
  IMAGE_NAME: api
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build image
        run: |
          cd remoodle/api

          IMAGE_ID=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's/[\/-]/_/g')

          # tag
          TAG=$IMAGE_ID:$VERSION

          # Change all uppercase to lowercase
          TAG=$(echo $TAG | tr '[A-Z]' '[a-z]')

          echo TAG=$TAG

          # Build the Docker image
          docker build . --file Dockerfile --tag $TAG

          # Docker Push
          docker push $TAG
