name: "[api] Publish Docker image"

on:
  push:
    branches: [main]
    paths:
      - "remoodle/api/**"
  workflow_dispatch:

env:
  IMAGE_NAME: api
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to ghcr
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          IMAGE_ID=ghcr.io/remoodle/api
          GITHUB_REF="${{ github.ref }}"

          echo IMAGE_ID=$IMAGE_ID
          echo GITHUB_REF=$GITHUB_REF

          cd remoodle/api
          docker pull $IMAGE_ID:latest
          docker build . --file Dockerfile --tag $IMAGE_ID:$IMAGE_TAG --cache-from $IMAGE_ID:latest
          docker build . --file Dockerfile --tag $IMAGE_ID:latest --cache-from $IMAGE_ID:$IMAGE_TAG

          docker push $IMAGE_ID:$IMAGE_TAG
          docker push $IMAGE_ID:latest
