name: "[backend] Release"

on:
  push:
    branches: [trunk]
    paths:
      - "apps/backend/**"
      - ".github/workflows/backend-release.yml"

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: wsehl/release-please-action@main
        id: release
        with:
          config-file: .release-please/config.json
          manifest-file: .release-please/manifest.json
          path: apps/backend
          token: ${{ steps.app-token.outputs.token }}
