name: "Release, backend"

on:
  push:
    branches: [trunk]
    paths:
      - "apps/backend/**"
      - ".github/workflows/backend-release.yml"

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: actions/checkout@v4
      - uses: wsehl/release-please-action@main
        id: release
        with:
          config-file: .release-please/config.json
          manifest-file: .release-please/manifest.json
          path: apps/backend

  # deploy-pr-preview:
  #   needs: release
  #   if: needs.release.outputs.release_created == 'true'
  #   uses: remoodle/heresy/.github/workflows/backend-docker.yml@trunk
