name: "Release, backend"

on:
  push:
    branches: [trunk]
    paths:
      - "remoodle/backend/**"
      - ".github/workflows/backend-release.yml"

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .release-please/config.json
          manifest-file: .release-please/manifest.json
          path: ./remoodle/backend
