name: "[backend] Publish Docker image"

on:
  push:
    branches: [trunk]
    paths:
      - "apps/backend/**"
      - ".github/workflows/backend-docker.yml"

  workflow_dispatch:

  workflow_call:
    inputs:
      release_version:
        required: true
        type: "string"

env:
  IMAGE_NAME: backend
  REGISTRY: ghcr.io

permissions: write-all

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Get latest tag
        id: latest_tag
        uses: ./.github/actions/latest-tag
        with:
          tag_prefix: "remoodle/backend-"

      - name: Build image
        env:
          RELEASE_VERSION: ${{ inputs.release_version }}
        run: |
          IMAGE_ID=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-8)

          if [[ -n "${RELEASE_VERSION}" ]]; then
            DOCKER_TAG="${RELEASE_VERSION}"
            VERSION_TAG="release-v${RELEASE_VERSION}.${SHORT_SHA}"
          else
            GITHUB_REF=$(echo "${{ github.ref }}" | sed -e 's/[\/-]/_/g')
            LATEST_TAG=${{ steps.latest_tag.outputs.result }}
            
            DOCKER_TAG="${GITHUB_REF}"
            VERSION_TAG="${LATEST_TAG}.${SHORT_SHA}::${GITHUB_REF}"
          fi

          echo IMAGE_ID=$IMAGE_ID
          echo DOCKER_TAG=$DOCKER_TAG

          docker build -f apps/backend/Dockerfile . --tag $IMAGE_ID:$DOCKER_TAG --build-arg VERSION_TAG=$VERSION_TAG

          docker push $IMAGE_ID:$DOCKER_TAG
