name: "[backend] Publish Docker image"

on:
  workflow_call:
  push:
    branches: [trunk]
    paths:
      - "apps/backend/**"
      - ".github/workflows/backend-docker.yml"
  workflow_dispatch:

env:
  IMAGE_NAME: backend
  REGISTRY: ghcr.io

permissions: write-all

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          IMAGE_ID=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}

          if [[ "${{ github.event_name }}" == "release" ]]; then
            # Extract tag name from refs/tags/<tag_name>
            VERSION=$(echo "${{ github.ref }}" | sed -e 's/refs\/tags\///')
          else
            # Strip git ref prefix from version
            VERSION=$(echo "${{ github.ref }}" | sed -e 's/[\/-]/_/g')
          fi

          # tag
          TAG=$IMAGE_ID:$VERSION

          # Change all uppercase to lowercase
          TAG=$(echo $TAG | tr '[A-Z]' '[a-z]')

          echo TAG=$TAG

          # Build the Docker image
          docker build -f apps/backend/Dockerfile . --tag $TAG

          # Docker Push
          docker push $TAG
