name: "CI"

on:
  push:

jobs:
  ci:
    name: Check types, formatting, lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node_version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.5

      - name: Install dependencies
        run: pnpm install

      - name: Check types
        run: pnpm type-check

      - name: Lint
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test
