on:
  workflow_call:

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64, vmi1641400, lg]
    steps:
      - name: Deploy
        run: |
          cd ~/remoodle
          docker compose pull && docker compose up -d
          docker compose ps
