name: "Trigger deploy"

on:
  registry_package:
    types: [published, updated]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Trigger deployment in remoodle-infra
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: remoodle/remoodle-infra
          event-type: deploy
          client-payload: '{"registry_package": "${{ github.event.registry_package }}"}'
