on:
  workflow_call:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          cd ~/remoodle
          docker compose pull && docker compose up -d
          docker compose ps
