name: "Trigger deploy"

on:
  registry_package:
    types: [published, updated]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment in remoodle-infra
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CI_TOKEN }}
          repository: remoodle/remoodle-infra
          event-type: deploy
          client-payload: '{"registry_package": ${{ toJson(github.event.registry_package) }}}'
