name: "Release, frontend"

on:
  push:
    branches: [trunk]
    paths:
      - "apps/frontend/**"
      - ".github/workflows/frontend-release.yml"

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      has_release_pr: ${{ steps.release-please.outputs.prs_created }}
      release_pr: ${{ steps.release-please.outputs.pr }}
      release_created: ${{ steps.release-please.outputs.releases_created }}
    steps:
      - uses: actions/checkout@v4
      - uses: wsehl/release-please-action@main
        id: release-please
        with:
          config-file: .release-please/config.json
          manifest-file: .release-please/manifest.json
          path: apps/frontend
          token: ${{ secrets.ROBOT_PAT }}

  deploy:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Install dependencies
        run: cd apps/frontend && pnpm install

      - name: Build app
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: cd apps/frontend && pnpm build-only

      - run: echo "ignore-workspace-root-check=true" >> .npmrc

      - name: Deploy on stage
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ vars.CF_ACCOUNT_ID }}
          command: pages deploy apps/frontend/dist --project-name="frontend-dev-svo" --branch="trunk"

      - name: Deploy on production
        if: needs.release.outputs.release_created == 'true'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ vars.CF_ACCOUNT_ID }}
          command: pages deploy apps/frontend/dist --project-name="frontend-prod-nqz" --branch="production"
