name: Self Approve Pull Request
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR Number"
        required: true

permissions:
  pull-requests: write
  contents: read

jobs:
  approve:
    if: contains('["notWhaleB", "wsehl"]', github.actor)
    runs-on: ubuntu-latest
    steps:
      - name: Approve Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.CI_TOKEN }}
          script: |
            const prNumber = context.payload.inputs.pr_number;

            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              event: 'APPROVE',
            });

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `Self-approved on behalf of ${{ github.actor }}`,
            });
