name: "[tgbot] Publish Docker image"

on:
  push:
    branches: [trunk]
    paths:
      - "apps/telegram-bot/**"
    tags:
      - "remoodle/telegram-bot-*"
  workflow_dispatch:

env:
  IMAGE_NAME: tgbot
  REGISTRY: ghcr.io

permissions: write-all

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Login to GitHub Container Registry (as bot)
        run: echo "${{ steps.app-token.outputs.token }}" | docker login ${{ env.REGISTRY }} -u migishh --password-stdin

      - name: Build image
        id: build-image
        run: |
          IMAGE_ID=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-8)
          ENVIRONMENT="staging"

          if [[ "${{ github.ref }}" =~ refs/tags/* ]]; then
            GITHUB_REF=$(echo "${{ github.ref }}" | sed -e 's/.*v//')
            ENVIRONMENT="production"
          else
            GITHUB_REF=$(echo "${{ github.ref }}" | sed -e 's/refs\/heads\///' | sed -e 's/[\/-]/_/g')
          fi

          DOCKER_TAG="${GITHUB_REF}"
          VERSION_TAG="v${GITHUB_REF}::${SHORT_SHA}"

          echo IMAGE_ID=$IMAGE_ID
          echo DOCKER_TAG=$DOCKER_TAG

          docker build -f apps/telegram-bot/Dockerfile . --tag $IMAGE_ID:$DOCKER_TAG --build-arg VERSION_TAG=$VERSION_TAG

          docker push $IMAGE_ID:$DOCKER_TAG
