name: "Release, web"

on:
  pull_request:
    branches: [trunk]
    paths:
      - "remoodle/frontend/web/**"
      - ".github/workflows/web-release.yml"

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      # has_release_pr: ${{ fromJSON(steps.find-pr.outputs.result).has_release_pr }}
      # release_pr: ${{ fromJSON(steps.find-pr.outputs.result).release_pr }}
      # release_created: ${{ contains(steps.release-please.outputs.paths_released, 'remoodle/frontend/web') }}

      has_release_pr: ${{ steps.release-please.outputs.prs_created }}
      release_pr: ${{ steps.release-please.outputs.pr }}
      release_created: ${{ steps.release-please.outputs.releases_created }}
    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          config-file: .release-please/config.json
          manifest-file: .release-please/manifest.json
          path: remoodle/frontend/web

      # - name: Find Release PR
      #   uses: actions/github-script@v7
      #   id: find-pr
      #   with:
      #     result-encoding: json
      #     script: |
      #       let prsJson = `${{ steps.release-please.outputs.prs }}`;

      #       if (!prsJson || prsJson.trim() === '') {
      #         console.log('No PRs data available or the data is empty.');
      #         return {
      #           release_pr: null,
      #           has_release_pr: 'false'
      #         };
      #       }

      #       prsJson = prsJson.replace(/("body":\s*")[^"]*(")/g, '$1$2');

      #       try {
      #         const prs = JSON.parse(prsJson);
      #         const targetPr = prs.find(pr => pr.title.includes('remoodle/web'));

      #         if (targetPr) {
      #           console.log('PR found for deployment:', targetPr);
      #           return {
      #             release_pr: JSON.stringify(targetPr),
      #             has_release_pr: 'true'
      #           };
      #         }
      #       } catch (error) {
      #         console.error('Error parsing PRs:', error);
      #       }

      #       return {
      #         release_pr: null,
      #         has_release_pr: 'false'
      #       };

  deploy-pr-preview:
    needs: release
    if: needs.release.outputs.has_release_pr == 'true'
    uses: remoodle/heresy/.github/workflows/web-preview.yml@trunk
    secrets: inherit
    with:
      title: ${{ fromJson(needs.release.outputs.release_pr).title }}
      number: ${{ fromJson(needs.release.outputs.release_pr).number }}
      branch: ${{ fromJson(needs.release.outputs.release_pr).headBranchName }}

  deploy:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "remoodle/frontend/web/pnpm-lock.yaml"

      - name: Install dependencies
        run: cd remoodle/frontend/web && pnpm install

      - name: Build app
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: cd remoodle/frontend/web && pnpm build-only

      - run: echo "ignore-workspace-root-check=true" >> .npmrc

      - name: Deploy on stage
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ vars.CF_ACCOUNT_ID }}
          command: pages deploy remoodle/frontend/web/dist --project-name="frontend-dev-svo" --branch="trunk"

      - name: Deploy on production
        if: needs.release.outputs.release_created == 'true'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ vars.CF_ACCOUNT_ID }}
          command: pages deploy remoodle/frontend/web/dist --project-name="frontend-prod-nqz" --branch="production"
