name: "Release, web"

on:
  push:
    branches: [trunk]
    paths:
      - "remoodle/frontend/web/**"
      - ".github/workflows/web-release.yml"

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      paths_released: ${{ steps.release.outputs.paths_released }}
      prs_created: ${{ steps.release.outputs.prs_created }}
      prs: ${{ steps.release.outputs.prs }}
      pr: ${{ steps.release.outputs.pr }}
    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .release-please/config.json
          manifest-file: .release-please/manifest.json

  check_prs:
    needs: release
    runs-on: ubuntu-latest
    outputs:
      pr_for_deployment: ${{ steps.find_pr.outputs.pr_for_deployment }}
    steps:
      - uses: actions/github-script@v7
        id: find_pr
        with:
          script: |
            const prs = JSON.parse('${{ needs.release.outputs.prs }}');
            const targetPr = prs.find(pr => pr.title.includes('remoodle/frontend/web'));
            if (targetPr) {
              console.log('PR found for deployment:', targetPr.number);
              return targetPr;
            }
            return null;
          result-encoding: string

  deploy-preview:
    needs: check_prs
    if: needs.check_prs.outputs.pr_for_deployment
    uses: remoodle/heresy/.github/workflows/web-preview.yml@trunk
    secrets: inherit
    with:
      title: ${{ fromJson(needs.check_prs.outputs.pr_for_deployment).title }}
      number: ${{ fromJson(needs.check_prs.outputs.pr_for_deployment).number }}
      branch: ${{ fromJson(needs.check_prs.outputs.pr_for_deployment).headBranchName }}

  deploy-stage-prod:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "remoodle/frontend/web/pnpm-lock.yaml"

      - name: Install dependencies
        run: cd remoodle/frontend/web && pnpm install

      - name: Build app
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: cd remoodle/frontend/web && pnpm build-only

      - run: echo "ignore-workspace-root-check=true" >> .npmrc

      - name: Deploy on stage
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ vars.CF_ACCOUNT_ID }}
          command: pages deploy remoodle/frontend/web/dist --project-name="frontend-dev-svo" --branch="trunk"

      - name: Deploy on production
        if: fromJson(needs.release.outputs.paths_released) && contains(needs.release.outputs.paths_released, 'remoodle/frontend/web')
        uses: cloudflare/wrangler-action@v3.6
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ vars.CF_ACCOUNT_ID }}
          command: pages deploy remoodle/frontend/web/dist --project-name="frontend-prod-nqz" --branch="production"
