name: "Release, web"

on:
  push:
    branches: [trunk]
    paths:
      - "remoodle/frontend/web/**"
      - ".github/workflows/web-release.yml"

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      pr: ${{ fromJSON(steps.find_pr.outputs.result).pr }}
      has_pr: ${{ fromJSON(steps.find_pr.outputs.result).has_pr }}
      paths_released: ${{ steps.release-please.outputs.paths_released }}
    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          config-file: .release-please/config.json
          manifest-file: .release-please/manifest.json

      - name: Find Release PR
        uses: actions/github-script@v7
        id: find_pr
        with:
          result-encoding: json
          script: |
            let prsJson = `${{ steps.release-please.outputs.prs }}`;

            if (!prsJson || prsJson.trim() === '') {
              console.log('No PRs data available or the data is empty.');
              return {
                pr: null,
                has_pr: 'false'
              };
            }

            prsJson = prsJson.replace(/("body":\s*")[^"]*(")/g, '$1$2');

            try {
              const prs = JSON.parse(prsJson);
              const targetPr = prs.find(pr => pr.title.includes('remoodle/web'));

              if (targetPr) {
                console.log('PR found for deployment:', targetPr);
                return {
                  pr: JSON.stringify(targetPr),
                  has_pr: 'true'
                };
              }
            } catch (error) {
              console.error('Error parsing PRs:', error);
            }

            return {
              pr: null,
              has_pr: 'false'
            };

  deploy-pr-preview:
    needs: release
    if: needs.release.outputs.has_pr == 'true'
    uses: remoodle/heresy/.github/workflows/web-preview.yml@trunk
    secrets: inherit
    with:
      title: ${{ fromJson(needs.release.outputs.pr).title }}
      number: ${{ fromJson(needs.release.outputs.pr).number }}
      branch: ${{ fromJson(needs.release.outputs.pr).headBranchName }}

  deploy:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "remoodle/frontend/web/pnpm-lock.yaml"

      - name: Install dependencies
        run: cd remoodle/frontend/web && pnpm install

      - name: Build app
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: cd remoodle/frontend/web && pnpm build-only

      - run: echo "ignore-workspace-root-check=true" >> .npmrc

      - name: Deploy on stage
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ vars.CF_ACCOUNT_ID }}
          command: pages deploy remoodle/frontend/web/dist --project-name="frontend-dev-svo" --branch="trunk"

      - name: Deploy on production
        if: fromJson(needs.release.outputs.paths_released) && contains(needs.release.outputs.paths_released, 'remoodle/frontend/web')
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ vars.CF_ACCOUNT_ID }}
          command: pages deploy remoodle/frontend/web/dist --project-name="frontend-prod-nqz" --branch="production"
