name: "Release, web"

on:
  push:
    branches: [trunk]
    paths:
      - "remoodle/frontend/web/**"
      - ".github/workflows/web-release.yml"

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      paths_released: ${{ steps.release.outputs.paths_released }}
      prs_created: ${{ steps.release.outputs.prs_created }}
      prs: ${{ steps.release.outputs.prs }}
      pr: ${{ steps.release.outputs.pr }}
    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .release-please/config.json
          manifest-file: .release-please/manifest.json

  check_prs:
    needs: release
    if: needs.release.outputs.prs_created == 'true'
    runs-on: ubuntu-latest
    outputs:
      deploy_needed: ${{ steps.filter_prs.outputs.deploy_needed }}
      pr_title: ${{ steps.filter_prs.outputs.pr_title }}
      pr_number: ${{ steps.filter_prs.outputs.pr_number }}
      pr_head_branch: ${{ steps.filter_prs.outputs.pr_head_branch }}
    steps:
      - name: Check PRs for Deployment
        id: filter_prs
        if: needs.release.outputs.prs_created == 'true'
        run: |
          PRS='${{ needs.release.outputs.prs }}'
          DEPLOY_NEEDED=false
          PR_TITLE=""
          PR_NUMBER=""
          PR_HEAD_BRANCH=""
          for ROW in $(echo "${PRS}" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${ROW} | base64 --decode | jq -r ${1}
            }
            TITLE=$(_jq '.title')
            NUMBER=$(_jq '.number')
            BRANCH=$(_jq '.headBranchName')
            if [[ "$TITLE" == *"remoodle/web"* ]]; then
              DEPLOY_NEEDED=true
              PR_TITLE="$TITLE"
              PR_NUMBER="$NUMBER"
              PR_HEAD_BRANCH="$BRANCH"
              break
            fi
          done
          echo "deploy_needed=$DEPLOY_NEEDED" >> $GITHUB_OUTPUT
          echo "pr_title=$PR_TITLE" >> $GITHUB_OUTPUT
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "pr_head_branch=$PR_HEAD_BRANCH" >> $GITHUB_OUTPUT

  deploy-preview:
    needs: [release, check_prs]
    if: needs.check_prs.outputs.deploy_needed == 'true'
    uses: remoodle/heresy/.github/workflows/web-preview.yml@trunk
    secrets: inherit
    with:
      title: ${{ needs.check_prs.outputs.pr_title }}
      number: ${{ needs.check_prs.outputs.pr_number }}
      branch: ${{ needs.check_prs.outputs.pr_head_branch }}

  deploy:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.5
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: cd remoodle/frontend/web && pnpm install

      - name: Build app
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: cd remoodle/frontend/web && pnpm build-only

      - run: cd remoodle/frontend/web && echo "ignore-workspace-root-check=true" >> .npmrc

      - name: Deploy on stage
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ vars.CF_ACCOUNT_ID }}
          command: pages deploy remoodle/frontend/web/dist --project-name="frontend-dev-svo" --branch="production"

      - name: Deploy on production
        if: needs.release.outputs.releases_created == 'true'
        uses: cloudflare/wrangler-action@v3.6
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ vars.CF_ACCOUNT_ID }}
          command: pages deploy remoodle/frontend/web/dist --project-name="frontend-prod-nqz" --branch="production"
